version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TEST_ALL_7825Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_test_all_7825.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsertNew
  packages:
  - name: SIQA_TEST_ALL_7825Project
    version: "1.0"
- serviceName: project.siqa_test_all_7825.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_TEST_ALL_7825Project
    version: "1.0"
- serviceName: project.siqa_test_all_7825.integrations:deepclonetest
  packages:
  - name: SIQA_TEST_ALL_7825Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
